### PR TITLE
Turkey Scala User Group 

### PR DESCRIPTION
**Pull request by mimaraslan**
Add Turkey Scala User Group

### CODE REVIEW

**Comment by mimaraslan** [comment]
Add 	Turkey Scala User Group

**Comment by octonato** [comment]
Hi @mimaraslan,

Only saw your PR now. I don't know why we I didn't receive a notification. Probably got lost on our inbox. Sorry for that.

**Comment by mimaraslan** [comment]
Dear Sir,

Turkey Scala Users Group, It was not on the map. Now invisible.
Can you help me please? We want it to appear.

http://scala.space/
As the cursor on the Scala icon disappear for Turkey Scala Users Group.

Best regards, Thank you**...*☕
Turkey Java User Group Leader,
Senior Java/Scala Developer,
Computer Engineer
Mimar Aslan

**Comment by mimaraslan** [comment]
Dear Sir,

http://scala.space/
Turkey Scala Users Group, It was not on the map. Now invisible.
When the cursor hovers over the icon disappears scala for Turkey Scala Users Group.
Can you help me please? We want it to appear.

Best regards, Thank you...☕
Turkey Java User Group Leader,
Senior Java/Scala Developer,
Computer Engineer
Mimar Aslan

**Comment by mimaraslan** [comment]
Dear Sir,

We love Scala in Turkey.

Please add to us on the map.





    {

      "name": "Turkey Scala User Group",

      "url": "www.turkeyjug.org",

      "latitude": 41.01453,

      "longitude": 29.01299,

      "justScala": true

    }





*Best regards, Thank you**...*☕
Turkey Java User Group Leader
*Mimar Aslan <https://www.linkedin.com/in/mimaraslan> *

*Best regards, Thank you**...*☕



*Turkey Java User Group Leader,Turkey Scala User Group Leader,Senior
Java/Scala/BigData Developer,Computer Engineer*
*Mimar Aslan <https://www.linkedin.com/in/mimaraslan> *

On Wed, Jun 22, 2016 at 1:05 AM, Renato Cavalcanti <notifications@github.com

**Comment by mimaraslan** [comment]
When the cursor hovers over the icon disappears scala for Turkey Scala Users Group.
Can you help me please? We want it to appear.

**Pull request merged**
