### PR TITLE
Potential restyling...

### PR DESCRIPTION
**Pull request by propensive**

### CODE REVIEW

**Comment by propensive** [comment]
@stefanobaghino I like it, and it solves the problem well! I think there's also scope for expanding the content with additional popups later on.

Can you rebase this against the current master, and I'll get it merged!

**Comment by stefanobaghino** [comment]
You may have noticed that I also introduced some changes, namely:
- moved the JS to an external script (instead of having it embedded in the markup)
- moved the groups to a second script `groups.js`
- moved the contribution instructions to `README.md`

I think they are improvements but I'd like to know what you'd like me to do with those.

**Comment by stefanobaghino** [comment]
I've rebased with my refactoring and it's ready to be merged, let me know if you prefer the old structure.

**Comment by propensive** [comment]
Looks good, live! Thanks @stefanobaghino!

**Pull request merged**
